HTCONDOR_MASTER_CONF_TEMPLATE = """
## USER defined bits
FLOCK_TO=$flock_host
HIGHPORT=9700
LOWPORT=9600
START=true
SUSPEND=false
"""

HTCONDOR_WOORKER_CONF_TEMPLATE = """
## USER defined bits
CONDOR_HOST=$host
HIGHPORT=9700
LOWPORT=9600
DAEMON_LIST=MASTER, STARTD, SCHEDD
"""
