# Generated by Django 2.2.10 on 2020-06-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HMInstallTemplate',
            fields=[
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('repo', models.SlugField(max_length=60)),
                ('chart', models.SlugField(max_length=60)),
                ('chart_version', models.CharField(blank=True, max_length=60, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('maintainers', models.TextField(blank=True, null=True)),
                ('info_url', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Install Template',
                'verbose_name_plural': 'Install Templates',
            },
        ),
    ]
