# Generated by Django 3.1.4 on 2021-01-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterman', '0002_create_rancher_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmautoscaler',
            name='allowed_vm_type_prefixes',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
