# Generated by Django 2.0.5 on 2018-05-21 13:23

from django.db import migrations
from django.core import serializers

# based on: https://stackoverflow.com/questions/32912112/django-loaddata-in-
# migrations-errors
def create_rancher_app(apps, schema_editor):
    original_apps = serializers.python.apps
    serializers.python.apps = apps
    fixture_file = 'cmcluster/fixtures/rancher_app_def.json'
    fixture = open(fixture_file)
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()
    serializers.python.apps = original_apps


class Migration(migrations.Migration):

    dependencies = [
        ('cmcluster', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_rancher_app)
    ]
