# Generated by Django 2.2.6 on 2019-11-01 13:38

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion


User = get_user_model()
try:
    default_owner = User.objects.filter(is_superuser=True).first().id
except:
    default_owner = None


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmproject',
            name='owner',
            field=models.ForeignKey(default=default_owner, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
