# Generated by Django 2.2.12 on 2020-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmproject',
            name='oidc_client_secret',
            field=models.CharField(default='changeme', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
